### ISSUE TITLE
change remote_hive configured external_id

### ISSUE THREAD

**Issue by bdenglish** [yukiegosapporo/2015-12-21-set-up-sublime-text-for-light-weight-all-in-one-data-science-ide#1]
In the Main.sublime-menu file for the hive example, the configured value for "external_id" should be changed from "shell" to "hive". Otherwise in order for the file to be recognized by the REPL the file must be a file of type "shell". Since sublime has a package for Apache Hive the default should be to use the hive file type.

**Comment by yukiegosapporo** [comment]
Thanks, shell -> hive works well after installing Apache Hive.
Also confirmed shell -> impala works, just in case you use impala too.
