### ISSUE TITLE
Add config for Windows

### ISSUE THREAD

**Issue by shawngiese** [yukiegosapporo/2015-12-21-set-up-sublime-text-for-light-weight-all-in-one-data-science-ide#3]
I was able to get Windows working with

"windows": ["powershell", "plink", "-t", "hortonworks", "R"]},

Powershell for the color encoding
plink to run from the command line (after setting it up the "hortonworks" session in putty and the key access in Pageant.
-t to keep the session open after sending the first command

Don't know about a clean close to the session though.

**Comment by yukiegosapporo** [comment]
Awesome! I don't have Windows env so can't test it now but glad that you got it working!
